### ISSUE TITLE
Fix Modifiers UI design

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1617]
I have just one word here. Crazy. This is no UI design, this is the absence of UI design and any common sense. Apply is now in a sub menu to hide it from the user? Orly?  -.-

And oh this crazy middle centered checkboxes. I really hope that i can catch these things. Because i fear that this is C code ...

![modifier](https://user-images.githubusercontent.com/13919702/84598447-25f88880-ae6b-11ea-8302-bd5b2f433d4f.jpg)

**Comment by ReinerBforartists** [comment]
:'3

![active](https://user-images.githubusercontent.com/13919702/84598595-39f0ba00-ae6c-11ea-9f25-797273bc2d12.jpg)

**Comment by ReinerBforartists** [comment]
Menu is in source\blender\modifiers\intern\MOD_ui_common.c

**Comment by ReinerBforartists** [comment]
:'3

On with manual ...

![doesntwork](https://user-images.githubusercontent.com/13919702/88451396-b658be80-ce56-11ea-8f94-11cae91d6fc0.jpg)

**Comment by ReinerBforartists** [comment]
The modifiers list addon does some changes at the modifier UI. Worth a look.

![modifiers](https://user-images.githubusercontent.com/13919702/99238726-5ff2ff80-27fa-11eb-9765-01669afb4239.jpg)

**Comment by iyadahmed** [comment]
hmm this is fixed in lts?
![image](https://user-images.githubusercontent.com/25552173/102912313-e3e97880-4485-11eb-9170-7edaeaa01f9c.png)

**Comment by ReinerBforartists** [comment]
It is not fixed, it was never changed in the lts. This change came with Blender 2.90. . Blender 2.83 LTS is the long term version, which keeps the old way for compatibility reason. Blender 2.92 and Bforartists uses this style now.

![newstyle](https://user-images.githubusercontent.com/13919702/102912907-49d20200-447e-11eb-884a-6d5ebd4a475b.jpg)

**Comment by ReinerBforartists** [comment]
What we should definitely do is to move the Apply button back to the row. It is very often needed. And i had today the misfortune that the hotkey applied the wrong modifier. Hotkey sucks here big time. Duplicate and move can remain in the sub menu. But apply should have a top level ui entry.

**Comment by iyadahmed** [comment]
> It is not fixed, it was never changed in the lts. This change came with Blender 2.90. . Blender 2.83 LTS is the long term version, which keeps the old way for compatibility reason. Blender 2.92 and Bforartists uses this style now.
> 
> ![newstyle](https://user-images.githubusercontent.com/13919702/102912907-49d20200-447e-11eb-884a-6d5ebd4a475b.jpg)

was writing the comment,
> What we should definitely do is to move the Apply button back to the row. It is very often needed. And i had today the misfortune that the hotkey applied the wrong modifier. Hotkey sucks here big time. Duplicate and move can remain in the sub menu. But apply should have a top level ui entry.

Indeed agree, I was thinking about moving the whole 4 buttons (only keeping move to first/last in the sub menu)

so the current most simple solution is to add these to the header (Apply, Apply as Shapekey, Save as Shapekey, Duplicate)
some are only showed for some nodes, like this (about to move the X remove button to the end)
![image](https://user-images.githubusercontent.com/25552173/102913942-3166e500-4488-11eb-9717-0fedd70dbb59.png)



 I tried creating another row below the header, but it glitched out and got drawn under the modifier panel UI (each modifier is a panel, and that top bar is a panel header)

I looked at the modifier list addon, it actually replaces the whole UI, so we could rewrite the whole thing.
another solution would be to add the button at the top of the panel for each modifier,
there are some other hacky solutions but all failed

**Comment by iyadahmed** [comment]
I believe a better design is something like this, what do you think?
![image](https://user-images.githubusercontent.com/25552173/102914956-b0a8e880-4489-11eb-8c01-3fb1fb8ab87c.png)

**Comment by iyadahmed** [comment]
Many thanks :)
I agree, I think we could keep it too, I could ask @Draise14  too

**Comment by ReinerBforartists** [comment]
I think he will agree :)

**Comment by iyadahmed** [comment]
> I think he will agree :)

Yep just asked, agree on hiding duplicate :)

**Comment by ReinerBforartists** [comment]
\o/
DO IT!

**Comment by iyadahmed** [comment]
> \o/
> DO IT!

Done :)
did testing, also moved the switch context operator (for physics modifiers) to the new operators row, it even fits nicely as these modifiers doesn't have a delete button
pushing and pr soon
![image](https://user-images.githubusercontent.com/25552173/102919538-b86c8b00-4491-11eb-9ef5-32e1a22d85ea.png)
