### ISSUE TITLE
3D View - Transform - Restrict axis with middle click 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1961]
# Issue
The transform changing to transform tool with Lclick to drag to view is great, W to activate is great. But there still is one modal feature missing - restrict axis with a gesture and the middle click. 

Right now it doesn't work with the middle click and gesture to restict axis. It only works with hotkeys. 

![image](https://user-images.githubusercontent.com/35357409/98144779-8c248d00-1e98-11eb-83fd-85a104720087.png)

The idea is to trigger these, but with middle click. 
![image](https://user-images.githubusercontent.com/35357409/98145268-cd1ca180-1e98-11eb-9a61-a8847d70b15f.png)

In vanilla Blender, this does work with middle click to restrict axis. 
![ChjuChRM3B](https://user-images.githubusercontent.com/35357409/98145149-bbd39500-1e98-11eb-90b3-44e1053b7ac7.gif)

To do this in blender, chose transform mode of G, then move then press the middle click. 

# Task
Review hotkey map to add the middle mouse button to the transform operator to restrict axis with middle mouse.

**Comment by ReinerBforartists** [comment]
Correct me if i am wrong, but this one belongs to 3D View - UX - Add world space navigation like in UE4 #1962 . It's the same issue, just with another hotkey.

**Comment by ReinerBforartists** [comment]
Ah, wait now i see what you mean. It's not exactly the same issue, but very closely related.

But we don't have the G functionality where you press G and the cube sticks to the mouse. Our navigation works with clicking and dragging. There is no transform action with a floating object where MMB could be called. When you want to restrict the movement to a plane then you have to use the plane constraint hotkey. That's for the groundplane the shift z hotkey.

We can add a MMB hotkey to Z plane. But that's very unhandy. And RMB ends the action, that's a conflict then.

Yes, Shift Z is hard to reach with an european hotkey layout. So what we could do is to add yet another hotkey to the Z Plane that is better to use. Ctrl Y for example. Works good from first tests. But this alternative hotkey does not appear in the footer tooltip then.


![zplane](https://user-images.githubusercontent.com/13919702/98215136-b1bc9f80-1f47-11eb-88c7-59389e7fcebf.jpg)


![zplanetooltip](https://user-images.githubusercontent.com/13919702/98215333-f34d4a80-1f47-11eb-8f48-e687b29eed06.jpg)

**Comment by ReinerBforartists** [comment]
There is just one transform modal map. And so the automatic constraint hotkey also shows in other editors. But no conflict so far.

**Comment by ReinerBforartists** [comment]
Fixed in master. Hotkey is now S

![autoconstraint](https://user-images.githubusercontent.com/13919702/98219668-9b194700-1f4d-11eb-9ecd-a7179564ac0a.jpg)

**Comment by Draise14** [comment]
Still not fixed. Test in blender in normal transform mode. It's not just in G but normal widget use. Use the widget with L mouse then middle click while dragging. Then try do this in BFA. Broken. The task is mouse functionality, not more hot keys! 

It is pretty easy to do as middle is used to pan and zoom. It is much easier than a hot key. If I wanted to restrict with a hot key. .. XYZ keys would have done it the way it was.

**Comment by ReinerBforartists** [comment]
The operator is Automatic Constraint. The middle mouse would conflict in the cases where you use the left mouse already. That's why i have set the hotkey for Automatic Constraint to S.

We are not Blender.

**Comment by Draise14** [comment]
But we also are not Hotkey biased. Come on! Blender would logically, as they have, put it all under hotkeys.

**Comment by Draise14** [comment]
I'll also have to make a video here to showcase why all in mouse on one hand is much better than post-modal hotkeys.

**Comment by Draise14** [comment]
Here is the video showcasing why Middle click is more intuitive and hotkeys in post-modal operations. 

[https://youtu.be/_eJIeSyqtNw](https://youtu.be/_eJIeSyqtNw)

**Comment by ReinerBforartists** [comment]
Thanks for the video.  But the functionality is already added back. With hotkey S. MMB makes no sense to me, i tried it out. You automaticallly release the left mouse for that, and then you are out of transform mode.

**Comment by Draise14** [comment]
I don't use the index finger on middle click, but the ring finger. As most mouse users do. You hold left click with index, then ring to middle click. Just like you would use ring finger for right click. 

If only the API allowed for Left click AND right click together. It's basically like that except in sequence.  

Hotkeys modals is a 2 to 3 step process, in 3 different locations on the keyboard WITH another hotkey. It should not be this way. Transform modals by hotkey is just not intuitive.

**Comment by ReinerBforartists** [comment]
I never use the ring finger, i use the left finger. And as told, then you interrupt the transformation. It is imho a bad default. And i don't want to have a dozen hotkeys for the same functionality.

But i noticed something else. In Blender with MMB the cube walks along the single axis then. In Bforartists it walks along a plane instead. Looking for the difference at the moment.

**Comment by ReinerBforartists** [comment]
Okay, the method that i have chosen here seems broken. We have two automatic constraint entries, and i picked the wrong 50%. Already reported to Blender here. And under observation.

https://developer.blender.org/T82423

**Comment by ReinerBforartists** [comment]
Not broken really. But the one is meant to move along a plane, and the other is meant to move along a single axis. The movement along a plane is a bit broken though from what i can see. And in Blender we have just the axis constraint. Not the Plane constraint. So let's have a look what turns out with the above fix.

**Comment by ReinerBforartists** [comment]
Second fix. I won't let go the S key since i don't want to break my fingers here. You prefer MMB, and it's the default from Blender. So it was just logical to add both.

And i have added the hotkey to move along a plane combined with alt key.

Task would be fixed when the autoconstraint along a plane would really do what it is called. But it doesn't. So let's wait what turns out with the fix.

**Comment by ReinerBforartists** [comment]
This taks is fixed. And the blender bug is also fixed. So closing.

We use the alt key, not the shift key. The shift key conflicts with the precision movement.
